### ISSUE TITLE
Support for application commands (slash commands)

### ISSUE THREAD

**Issue by paulhagen** [kaname-png/neko-plugins#34]
Hey there,

I came by and noticed the plugin isn't working with the new slash commands yet? Sapphire is supporting them in the upcoming version 3.0. Is there a way to support it with autopost right now or do I have to wait for the full release of sapphire to be supported by the statcord plugin?

Greetings

**Comment by sawa-ko** [comment]
Hi, thanks for using the plugins!

About the support of slash commands, of course, they will be supported in Statcord plugin once @sapphire/framework is officially released with slash commands.

The plugin doesn't use beta versions because we have to be updating the dependency several times and be aware of new changes that are made. While if we wait for the stable version we already know what we have to do easily.

So don't worry, Statcord plugin will be updated to support slash commands as soon as @sapphire/framework makes them officially available. :)

**Comment by paulhagen** [comment]
Glad to hear! Looking forward to it, until then I will send command usage data manually :)

**Comment by sawa-ko** [comment]
Hi @paulhagen,

The latest version was updated to work with `@sapphire/framework@next`.
